### ISSUE TITLE
Pytorch failed while testing on CPU

### ISSUE THREAD

**Issue by yiyunya** [bethgelab/foolbox#136]
It seems that the pytorch module does not work if one is debugging on one's laptop's CPU.
Is it possible to add an entrance for CPU?

**Comment by jonasrauber** [comment]
It should work fine with the CPU-only version of PyTorch. In fact, we even run our automatic tests like this. Could you provide more information regarding the exact error and the Foolbox, Python and PyTorch version you use?

**Comment by yiyunya** [comment]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/yingliu/workspaces/ClassifierPlayground/average.py", line 20, in <module>
    adversarial = attack(image, label)
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/foolbox/attacks/base.py", line 88, in wrapper
    a = Adversarial(model, criterion, input_or_adv, label)
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/foolbox/adversarial.py", line 61, in __init__
    self.predictions(original_image)
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/foolbox/adversarial.py", line 240, in predictions
    predictions = self.__model.predictions(image)
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/foolbox/models/base.py", line 122, in predictions
    return np.squeeze(self.batch_predictions(image[np.newaxis]), axis=0)
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/foolbox/models/pytorch.py", line 62, in batch_predictions
    images = images.cuda()
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 384, in _lazy_new
    _lazy_init()
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 141, in _lazy_init
    _check_driver()
  File "/Users/yingliu/workspaces/python_3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 55, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled


I loaded the pretrained resnet from torchvision. Python 3.6.1,  Pytorch 3.10 and the newest Toolbox.
Or is it possible for you to release an example for pytorch? Maybe it is my code's problem.

**Comment by jonasrauber** [comment]
pass `cuda=False` when instantiating `foolbox.models.PyTorchModel` …

maybe we should auto-detect instead this instead of assuming `cuda=True` by default 🤔

**Comment by yiyunya** [comment]
OK I fixed that one. But it reported error at the channel size.
I have tried to change the channel_axis but it reported:
RuntimeError: Given groups=1, weight[64, 3, 7, 7], so expected input[1, 224, 224, 3] to have 3 channels, but got 224 channels instead
Well, do you have examples for Pytorch?

**Comment by jonasrauber** [comment]
Probably you are passing images in a different format than what is expected by your pytorch model. NCHW vs. NHWC. Please provide code.

**Comment by jonasrauber** [comment]
Closing because it seems to be solved.
