### ISSUE TITLE
AttributeError: 'DenseNet' object has no attribute 'bounds'

### ISSUE THREAD

**Issue by miltonbd** [bethgelab/foolbox#155]
Hello 
I found this while loading a model in pytorch. 

import foolbox
import torch
import torchvision
import numpy as np
from student_net_learning import model_loader

torchmodel = model_loader.get_model_net("")
torchmodel.eval()
model = foolbox.models.PyTorchModel(torchmodel, bounds=(0, 255), num_classes=512)

# get source image and label
image, label = foolbox.utils.imagenet_example()

# apply attack on source image
# ::-1 reverses the color channels, because Keras ResNet50 expects BGR instead of RGB
attack = foolbox.attacks.FGSM(torchmodel)
img=torch.from_numpy(np.flip(image[:, :, ::-1],axis=0).copy())
img=img.unsqueeze(0)
print(img.shape)
adversarial = attack(img, label)

import matplotlib.pyplot as plt

plt.figure()

plt.subplot(1, 3, 1)
plt.title('Original')
plt.imshow(image / 255)  # division by 255 to convert [0, 255] to [0, 1]
plt.axis('off')

plt.subplot(1, 3, 2)
plt.title('Adversarial')
plt.imshow(adversarial[:, :, ::-1] / 255)  # ::-1 to convert BGR to RGB
plt.axis('off')

plt.subplot(1, 3, 3)
plt.title('Difference')
difference = adversarial[:, :, ::-1] - image
plt.imshow(difference / abs(difference).max() * 0.2 + 0.5)
plt.axis('off')

plt.show()

following error:

Traceback (most recent call last):
  File "/media/milton/ssd1/research/competitions/mcs_2018_adversarial_attack/foolbox_attack.py", line 22, in <module>
    adversarial = attack(img, label)
  File "/usr/local/lib/python3.5/dist-packages/foolbox/attacks/base.py", line 88, in wrapper
    a = Adversarial(model, criterion, input_or_adv, label)
  File "/usr/local/lib/python3.5/dist-packages/foolbox/adversarial.py", line 61, in __init__
    self.predictions(original_image)
  File "/usr/local/lib/python3.5/dist-packages/foolbox/adversarial.py", line 236, in predictions
    in_bounds = self.in_bounds(image)
  File "/usr/local/lib/python3.5/dist-packages/foolbox/adversarial.py", line 194, in in_bounds
    min_, max_ = self.bounds()
  File "/usr/local/lib/python3.5/dist-packages/foolbox/adversarial.py", line 187, in bounds
    min_, max_ = self.__model.bounds()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 398, in __getattr__
    type(self).__name__, name))
AttributeError: 'DenseNet' object has no attribute 'bounds'

please help

Regards
Milton

**Comment by oGkgN** [comment]
In the line

    attack = foolbox.attacks.FGSM(torchmodel)

you use the `torchmodel` but should use the foolbox wrapper `model`. Changing that line to

    attack = foolbox.attacks.FGSM(model)

should resolve the issue.

**Comment by jonasrauber** [comment]
Thanks @oGkgN.
Assuming this is fixed and closing it.
