### ISSUE TITLE
Use two different models in "foolbox.models.CompositeModel"

### ISSUE THREAD

**Issue by walegahaha** [bethgelab/foolbox#187]
It seems that we can't use tf model as forward_model and pytorch model as backward_model at the same time, is that right?

=========================================
model = foolbox.models.CompositeModel(
     forward_model=forward_model,
     backward_model=backward_model)

=========================================
foolbox/models/wrappers.py

channel_axis = forward_model.channel_axis()
assert channel_axis == backward_model.channel_axis()

**Comment by jonasrauber** [comment]
You can, you just need to make sure they expect the same type of input, e.g. same shape and range of values. TensorFlow models usually support both, CHW, and HWC, so that might be easy to achieve by slightly modifying your TensorFlow model. Alternatively, you can specify the preprocessing Foolbox by passing a function to the preprocessing argument when creating the Foolbox model (experimental support added in Foolbox 1.3; not yet documented); the function should do return the preprocessed input and a function that will backprop the gradient through the preprocessing (or None if you don't need gradients). For example, you could pass a function to the PyTorch model that converts HWC to CHW and then specify channel_axis=3.

**Comment by walegahaha** [comment]
@jonasrauber  Thanks!

**Comment by walegahaha** [comment]
@jonasrauber  This is the code and the error,  whatever I change the "grad function", it always has an error
`   model = EnsembleNet()
    model.eval()
    def preprocessing(image):
        image_shape = image.shape
        image = np.transpose(image, (2, 0 ,1)).astype(np.float32)
        def grad(dmdp):
            dmdp = np.transpose(dmdp, (1, 2 ,0)).astype(np.float32)
            return dmdp
        return image, grad

    fmodel = PyTorchModel(model, bounds=(0,255), num_classes=200, channel_axis=3, preprocessing=preprocessing)
`

`File "foolbox/models/pytorch.py", line 153, in predictions_and_gradient:
grad_shape: (3, 64, 64), image_shape (3, 64, 64)

File "foolbox/adversarial.py", line 331, in gradient:
gradient_shape: (3, 64, 64), image_shape (64, 64, 3)

Traceback (most recent call last):
  File "test.py", line 187, in <module>
    main()
  File "test.py", line 180, in main
    test(model, run_attack_fgsm,        "FGSM")
  File "test.py", line 140, in test
    adversarial = attack_func(model, image, label)
  File "test.py", line 113, in run_attack_fgsm
    return attack(image, label, epsilons=100)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/foolbox/attacks/base.py", line 97, in wrapper
    _ = call_fn(self, a, label=None, unpack=None, **kwargs)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/foolbox/attacks/gradient.py", line 90, in __call__
    return self._run(a, epsilons=epsilons, max_epsilon=max_epsilon)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/foolbox/attacks/gradient.py", line 25, in _run
    gradient = self._gradient(a)
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/foolbox/attacks/gradient.py", line 94, in _gradient
    gradient = a.gradient()
  File "/home/walegahaha/env/pytorch/lib/python3.5/site-packages/foolbox/adversarial.py", line 333, in gradient
    assert gradient.shape == image.shape`

**Comment by jonasrauber** [comment]
Hi @walegahaha, you are right, that's a bug in Foolbox. Will fix it asap. Independent of that, you should add `assert image.ndim == 3` and `assert dmdp.ndim == 3` to your preprocessing function, because there can be cases where it will be called with batches and if that were the case for you, you would need to handle that case separately (but for now, adding an assertion should be sufficient).

**Comment by walegahaha** [comment]
@jonasrauber  Okay，thanks

**Comment by jonasrauber** [comment]
I just released a new Foolbox version (1.3.2). With that one, changing the shape in the preprocessing function is fully supported:

Standard PyTorch example from the docs:
```python3
import torchvision.models as models
import numpy as np
import foolbox

resnet18 = models.resnet18(pretrained=True).cuda().eval()  # for CPU, remove cuda()
mean = np.array([0.485, 0.456, 0.406]).reshape((3, 1, 1))
std = np.array([0.229, 0.224, 0.225]).reshape((3, 1, 1))
model = foolbox.models.PyTorchModel(
    resnet18, bounds=(0, 1), num_classes=1000,
    preprocessing=(mean, std), channel_axis=1)

image, label = foolbox.utils.imagenet_example(data_format='channels_first')
image = image / 255
print(np.argmax(model.predictions(image)), label)
print(foolbox.utils.softmax(model.predictions(image))[label])

attack = foolbox.attacks.GradientAttack(model)
adv = attack(image, label, unpack=False)
print(adv.distance)
```

Modified PyTorch example with a preprocessing function converting from (N)HWC to (N)CHW:
```python3
import torchvision.models as models
import numpy as np
import foolbox

resnet18 = models.resnet18(pretrained=True).cuda().eval()  # for CPU, remove cuda()

def preprocessing(x):
    mean = np.array([0.485, 0.456, 0.406]).astype(x.dtype)
    std = np.array([0.229, 0.224, 0.225]).astype(x.dtype)
    x = (x - mean) / std
    assert x.ndim in [3, 4]
    if x.ndim == 3:
        x = np.transpose(x, axes=(2, 0, 1))
    elif x.ndim == 4:
        x = np.transpose(x, axes=(0, 3, 1, 2))
    def grad(dmdp):
        assert dmdp.ndim == 3
        dmdx = np.transpose(dmdp, axes=(1, 2, 0))
        dmdx = dmdx / std
        return dmdx
    return x, grad

model = foolbox.models.PyTorchModel(
    resnet18, bounds=(0, 1), num_classes=1000,
    preprocessing=preprocessing, channel_axis=3)

image, label = foolbox.utils.imagenet_example(data_format='channels_last')
image = image / 255
print(np.argmax(model.predictions(image)), label)
print(foolbox.utils.softmax(model.predictions(image))[label])

attack = foolbox.attacks.GradientAttack(model)
adv = attack(image, label, unpack=False)
print(adv.distance)
```

Both scripts output:
```
282 282
0.4404697
normalized MSE = 3.99e-08
```

**Comment by jonasrauber** [comment]
@walegahaha Let me know if this solved your problem

**Comment by walegahaha** [comment]
@jonasrauber It works! Your help was greatly appreciated!
