### ISSUE TITLE
cifar10 keras load_model error

### ISSUE THREAD

**Issue by gmt710** [bethgelab/foolbox#226]
D:\Users\Python\python3.exe D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py", line 72, in <module>
    main()
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial/MisClassification.py", line 18, in main
    kmodel = load_model('D:\\pythonwork\\Adversarial\\Cifar10_keras_Adversarial\\model\\lenet.h5')
  File "D:\Users\Python\lib\site-packages\keras\engine\saving.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\engine\saving.py", line 335, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Users\Python\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "D:\Users\Python\lib\site-packages\keras\engine\sequential.py", line 292, in from_config
    custom_objects=custom_objects)
  File "D:\Users\Python\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "D:\Users\Python\lib\site-packages\keras\utils\generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown layer:layers

Process finished with exit code 1

**Comment by jonasrauber** [comment]
This has nothing to do with Foolbox (the error message is thrown by Keras and Foolbox is not involved up to that point)
