### ISSUE TITLE
Deepfool attack,ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by gmt710** [bethgelab/foolbox#236]
- keras=2.2.4
- tensorflow=1.10.0
- foolbox=1.2.0

keras with the backend of tensorflow.
when I run the code of Deepfool attack, the program was ended by the error.

```
step:218,Error classification!
step:219,Succeed attack! pre_label:9,adv_label:1
Traceback (most recent call last):
  File "D:\Users\Python\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
AttributeError: 'list' object has no attribute 'argmin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial(20181025)/Mis+testAdv_nodp_dat.py", line 198, in <module>
    Mis(save_dat_path, save_txt_path, adv_mode, model_name)
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial(20181025)/Mis+testAdv_nodp_dat.py", line 104, in Mis
    adversarial = adversarial_attack(adv_mode, attack, image, pre_label)
  File "D:/pythonwork/Adversarial/Cifar10_keras_Adversarial(20181025)/Mis+testAdv_nodp_dat.py", line 70, in adversarial_attack
    adversarial = attack(input_or_adv=image, label=pre_label)
  File "D:\Users\Python\lib\site-packages\foolbox\attacks\base.py", line 97, in wrapper
    _ = call_fn(self, a, label=None, unpack=None, **kwargs)
  File "D:\Users\Python\lib\site-packages\foolbox\attacks\deepfool.py", line 144, in __call__
    optimal = np.argmin(distances)
  File "D:\Users\Python\lib\site-packages\numpy\core\fromnumeric.py", line 1068, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "D:\Users\Python\lib\site-packages\numpy\core\fromnumeric.py", line 62, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "D:\Users\Python\lib\site-packages\numpy\core\fromnumeric.py", line 42, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```

I search the Internet for this mistake, may be errors in the following a few words in the code.

```
deepfool.py（line133-144）

            # calculate distances
            if p == 2:
                distances = [abs(dl) / (np.linalg.norm(dg) + 1e-8)
                             for dl, dg in diffs]
            elif p == np.inf:
                distances = [abs(dl) / (np.sum(np.abs(dg)) + 1e-8)
                             for dl, dg in diffs]
            else:  # pragma: no cover
                assert False

            # choose optimal one
            optimal = np.argmin(distances)
```
Online search suggestions, maybe I can make the following changes:
```
            # calculate distances
            if p == 2:
                distances =(abs(dl) / (np.linalg.norm(dg) + 1e-8)
                             for dl, dg in diffs)
            elif p == np.inf:
                distances = (abs(dl) / (np.sum(np.abs(dg)) + 1e-8)
                             for dl, dg in diffs)
            else:  # pragma: no cover
                assert False

            # choose optimal one
            optimal = np.argmin(distances)
```
I download foolbox library, because there is no permission to modify the code, only read-only access, I haven't been able to solve my problem. I want to consult you on here. Thank you very much.

**Comment by jonasrauber** [comment]
As I answered in #249, you are most likely trying to use DeepFool with some special criterion like `ConfidentMisclassification`. DeepFool is basically designed for `Misclassifcation` only. I am closing this as we will track the issue here: #249
