### ISSUE TITLE
script frozen after executing boundary attack

### ISSUE THREAD

**Issue by VigneshSrinivasan10** [bethgelab/foolbox#274]
Hi, 

I have been trying to run the boundary attack on MNIST. 

Everything seemed good so far until some of the scripts freeze after executing the attack. Nothing happens for a long time (~overnight) until I kill the process. 
I am sharing the last thing visible on the screen. 

```
batch size was 25, optimal batch size would have been 10
setting batch size to 10: expected step duration: 0.00754
improvement compared to old batch size (25): 1.0x
improvement compared to worst batch size (1): 5.7x
improvement compared to smallest batch size (1): 5.7x
improvement compared to largest batch size (25): 1.0x
next batch size tuning in 800 steps, after step 5500
  Success rate too low, decreasing source step:  0.29 (100), 0.13 (30)
Step 4800: 3.19581e-07, stepsizes = 6.7e-03/2.3e-05: d. reduced by 0.00% (1.4294e-11) (took 0.06273 seconds)
Step 4900: 3.18372e-07, stepsizes = 6.7e-03/2.3e-05: d. reduced by 0.00% (1.4216e-11) (took 0.05084 seconds)
Step 5000: 3.17370e-07, stepsizes = 6.7e-03/2.3e-05: d. reduced by 0.00% (1.4113e-11) (took 0.03348 seconds)
Time since beginning: 214.21827
   78.0% for generation (167.03623)
   2.8% for spherical prediction (5.92751)
   16.0% for prediction (34.31870)
   0.2% for hyperparameter update (0.40839)
   3.0% for the rest (6.52744)


``` 
I am unable to find if any particular image is causing it as when I try to debug, the code runs smoothly. 

My question is: 
If you have ever come across this issue and know a way to solve this issue - then it would be great to know about it. 

Thanks in advance,

**Comment by VigneshSrinivasan10** [comment]
I think it might have something to do with the multi-threading. When I kill the process manually, I get this: 
```
^CTraceback (most recent call last):
  File "attack_mnist.py", line 135, in <module>
    main()
  File "attack_mnist.py", line 104, in main
    adversarial = attack(x_batch, y_batch, unpack=False, verbose=True, tune_batch_size=True)
  File "python3.6/site-packages/foolbox/attacks/base.py", line 138, in wrapper
    _ = call_fn(self, a, label=None, unpack=None, **kwargs)
  File "python3.6/site-packages/foolbox/attacks/boundary_attack.py", line 158, in __call__
    threaded_gen=threaded_gen)
  File "python3.6/site-packages/foolbox/attacks/boundary_attack.py", line 176, in _apply_outer
    return self._apply_inner(pool, *args, **kwargs)
  File "python3.6/concurrent/futures/_base.py", line 611, in __exit__
    self.shutdown(wait=True)
  File "python3.6/concurrent/futures/thread.py", line 152, in shutdown
    t.join()
  File "python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Exception ignored in: <bound method tqdm.__del__ of 67it [5:16:09, 111.86s/it]>
Traceback (most recent call last):
  File "python3.6/site-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "python3.6/site-packages/tqdm/_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "python3.6/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "python3.6/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

I am sorry that I am unable to provide anything more than this. I am running a very simple code similar to the code provided in my previous issue: 
https://github.com/bethgelab/foolbox/issues/272

Any pointers would be greatly appreciated. 

Thanks,
