### ISSUE TITLE
Error when attacking MNIST dataset

### ISSUE THREAD

**Issue by cli0** [bethgelab/foolbox#359]
I want to generate adversarial examples for MNIST but I always get a shape related error message. I looked at old MNIST related issues and made the appropriate fixes but it still won't work.

Code:

```
import numpy as np
import foolbox
from foolbox.attacks import CarliniWagnerL2Attack, FGSM
from foolbox.criteria import Misclassification
from foolbox.criteria import TargetClassProbability
from keras.datasets import mnist
import keras


if __name__ == '__main__':
    (x_train, y_train),(x_test, y_test) = mnist.load_data()
    x_train = x_train.reshape(-1,28,28,1)/255.0
    x_test = x_test.reshape(-1,28,28,1)/255.0

    keras.backend.set_learning_phase(0)
    model = keras.models.load_model("model.h5")
    fmodel = foolbox.models.KerasModel(model, bounds=(0, 255))

    # run the attack
    attack = CarliniWagnerL2Attack(model=fmodel)

    adv_images = []

    for i in range(len(x_test)):
        img = x_test[i]
        adv_images.append(attack(img, y_test[i]))
    np.save('x_adv_test.npy', adv_images)
```

Error code:

```
Traceback (most recent call last):
  File "/home/clio/Desktop/generate_adv.py", line 32, in <module>
    adv_images.append(attack(img, y_test[i]))
  File "/home/clio/Desktop/venv/lib/python3.6/site-packages/foolbox/attacks/base.py", line 137, in wrapper
    _ = call_fn(self, a, label=None, unpack=None, **kwargs)
  File "/home/clio/Desktop/venv/lib/python3.6/site-packages/foolbox/attacks/carlini_wagner.py", line 149, in __call__
    confidence, min_, max_)
  File "/home/clio/Desktop/venv/lib/python3.6/site-packages/foolbox/attacks/carlini_wagner.py", line 222, in loss_function
    is_adv_loss_grad = a.backward(logits_diff_grad, x)
  File "/home/clio/Desktop/venv/lib/python3.6/site-packages/foolbox/adversarial.py", line 449, in backward
    gradient = self.__model.backward(gradient, image)
  File "/home/clio/Desktop/venv/lib/python3.6/site-packages/foolbox/models/keras.py", line 180, in backward
    assert gradient.shape == image.shape
AssertionError
```
In the assertion error, the image shape is (28,28,1) and the gradient shape is (1,28,28,1). I tried reshaping the image to (1,28,28,1) but it does not get recognized down the line and is still seen as (28,28,1). Error persists.

What am I doing wrong here?

**Comment by jonasrauber** [comment]
Which Foolbox version are you using?

**Comment by jonasrauber** [comment]
closing due to lack of activity; please reopen if this is still an issue

**Comment by cli0** [comment]
Hi, I am sorry for not being able to reply sooner. I was using an old version, hence that particular error. I updated foolbox to 2.3 but now I get another type of error across the board
```

Traceback (most recent call last):
  File "/home/clio/Desktop/adversarial_generation.py", line 26, in <module>
    adv_images.append(attack(img, y_test[i]))
  File "/home/clio/Desktop/venv/lib/python3.6/site-packages/foolbox/attacks/base.py", line 25, in __call__
    assert isinstance(labels, np.ndarray)
AssertionError
```

**Comment by jonasrauber** [comment]
The error message says it all: `labels` should be a NumPy array
Note: Foolbox 2 assumes that you pass a batch of inputs and labels to the attack, not just a single one
