### ISSUE TITLE
Error in attacking a model loaded from model zoo

### ISSUE THREAD

**Issue by nickpezzotti1** [bethgelab/foolbox#516]
```
import torchvision
from torch.utils.data import DataLoader
import foolbox
from foolbox import zoo

# Get data
dl = DataLoader(torchvision.datasets.MNIST('path_to_file_if_exists', train=True, download=True,
                                           transform=torchvision.transforms.Compose([
                                               torchvision.transforms.ToTensor(),
                                           ])),

                batch_size=2)

iter = enumerate(dl)
next(iter)
index, batch = next(iter)
image, label = batch


url = "https://github.com/bethgelab/AnalysisBySynthesis"
fmodel = zoo.get_model(url)
attack_model  = foolbox.attacks.FGSM(fmodel, distance=foolbox.distances.Linf)

adversarial = attack_model(image.detach().cpu().reshape(2, 1, 28, 28).numpy(), label.detach().cpu().numpy(), unpack=False)
```

```
Traceback (most recent call last):
  File "/Users/nickpezzotti/Desktop/untitled/test.py", line 24, in <module>
    adversarial = attack_model(image.detach().cpu().reshape(2, 1, 28, 28).numpy(), label.detach().cpu().numpy(), unpack=False)
  File "/Users/nickpezzotti/Desktop/untitled/venv/lib/python3.7/site-packages/foolbox/attacks/base.py", line 52, in __call__
    **kwargs,
  File "/Users/nickpezzotti/Desktop/untitled/venv/lib/python3.7/site-packages/foolbox/batching.py", line 350, in run_parallel
    gradients = model.gradient(*gradients_args)
  File "/Users/nickpezzotti/Desktop/untitled/venv/lib/python3.7/site-packages/foolbox/models/pytorch.py", line 174, in gradient
    loss.backward()
  File "/Users/nickpezzotti/Desktop/untitled/venv/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/Users/nickpezzotti/Desktop/untitled/venv/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by jonasrauber** [comment]
Which Foolbox version are you using?
If you are using Foolbox 3, you should pass a PyTorch Tensor, not a NumPy array.
Does that work?

**Comment by zimmerrol** [comment]
CLosing due to inactivity from OP.
