### ISSUE TITLE
 ImportError: DLL load failed: The network path was not found.

### ISSUE THREAD

**Issue by JanineCHEN** [bethgelab/foolbox#519]
I have installed foolbox via `pip install foolbox`, but when I tried to `import foolbox`, I got the following error:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\foolbox\__init__.py", line 13, in <module>
    from . import attacks  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\foolbox\attacks\__init__.py", line 3, in <module>
    from .base import Attack
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\foolbox\attacks\base.py", line 6, in <module>
    from ..v1.attacks.base import Attack as BaseAttack
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\foolbox\v1\__init__.py", line 1, in <module>
    from . import attacks  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\foolbox\v1\attacks\__init__.py", line 6, in <module>
    from .lbfgs import LBFGSAttack, ApproximateLBFGSAttack
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\foolbox\v1\attacks\lbfgs.py", line 4, in <module>
    import scipy.optimize as so
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\scipy\optimize\__init__.py", line 389, in <module>
    from .optimize import *
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "C:\ProgramData\Anaconda3\envs\foolbox\lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: The network path was not found.
```
Any idea why this could happen, or should I install it via some other approaches?

**Comment by jonasrauber** [comment]
`from scipy.optimize import minpack2` fails, or more generally `import scipy.optimize as so`. That's a problem with importing scipy, not foolbox. Maybe check if scipy is properly installed or raise the issue there.
