### ISSUE TITLE
Cant feed pytorch tensor

### ISSUE THREAD

**Issue by ziqi-zhang** [bethgelab/foolbox#525]
Hi, I'm trying to feed pytorch tensor but encounter the following problem. It seems an incompatible problem with eagerpy.

Here is my code:
```
model = foolbox.models.PyTorchModel(model, bounds=(0, 1), preprocessing=preprocessing)
attack = fa.FGSM()
epsilon = 2/255
for batch_idx, (inputs, targets) in enumerate(test_loader):
    inputs, targets = inputs.to(device), targets.to(device)
    inputs = ep.astensor(inputs)
    targets = ep.astensor(targets)
    _, _, success = attack(model, inputs, targets, epsilons=epsilon)
```
And the error is:
```
Traceback (most recent call last):
  File "defects/adversarial/attack.py", line 116, in <module>
    main()
  File "defects/adversarial/attack.py", line 103, in main
    _, _, success = attack(model, inputs, targets, epsilons=epsilon)
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/foolbox/attacks/base.py", line 279, in __call__
    xp = self.run(model, x, criterion, epsilon=epsilon, **kwargs)
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/foolbox/attacks/gradient_descent_base.py", line 91, in run
    _, gradients = self.value_and_grad(loss_fn, x)
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/foolbox/attacks/gradient_descent_base.py", line 55, in value_and_grad
    return ep.value_and_grad(loss_fn, x)
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/eagerpy/framework.py", line 346, in value_and_grad
    return t.value_and_grad(f, *args, **kwargs)
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/eagerpy/tensor/tensor.py", line 537, in value_and_grad
    return self._value_and_grad_fn(f, has_aux=False)(self, *args, **kwargs)
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/eagerpy/tensor/pytorch.py", line 481, in value_and_grad
    loss = f(x, *args, **kwargs)
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/foolbox/attacks/gradient_descent_base.py", line 45, in loss_fn
    return ep.crossentropy(logits, labels).sum()
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/eagerpy/framework.py", line 315, in crossentropy
    return logits.crossentropy(labels)
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/eagerpy/tensor/pytorch.py", line 445, in crossentropy
    if self.ndim != 2:
  File "/home/zzq/anaconda3/envs/defect/lib/python3.6/site-packages/eagerpy/tensor/base.py", line 115, in ndim
    return cast(int, self.raw.ndim)
AttributeError: 'Tensor' object has no attribute 'ndim'
```
In the `logits.crossentropy` it will call `self.ndim` (`logits.ndim`). It will call `self.raw.ndim`, but pytorch Tensor object does not have ndim attribute. Is it an incompatible problem of eagerpy? My toolbox version is 3.0.0 and eagerpy version is 0.27.0.

Thanks!

**Comment by ziqi-zhang** [comment]
It's because I used PyTorch 1.1.0 and foolbox 3.0.0. When I downgrade toolbox to 2.0.0 the problem fixes.
