### ISSUE TITLE
Syntax Error (eagerpy)

### ISSUE THREAD

**Issue by kayush95** [bethgelab/foolbox#537]
I am trying to run the 'pytorch_resnet18.py' in the examples folder.
Currently, I am using python version 3.5.2 and pytorch version 1.4.0.

I am getting this error.

Traceback (most recent call last):
  File "pytorch_resnet18.py", line 3, in <module>
    import eagerpy as ep
  File "/afs/cs.stanford.edu/u/kayush/spring2020/informationBottleneck/cib/lib/python3.5/site-packages/eagerpy/__init__.py", line 21, in <module>
    from .tensor import Tensor  # noqa: F401
  File "/afs/cs.stanford.edu/u/kayush/spring2020/informationBottleneck/cib/lib/python3.5/site-packages/eagerpy/tensor/__init__.py", line 1, in <module>
    from .tensor import Tensor  # noqa: F401
  File "/afs/cs.stanford.edu/u/kayush/spring2020/informationBottleneck/cib/lib/python3.5/site-packages/eagerpy/tensor/tensor.py", line 544
    **kwargs: Any,
                 ^
SyntaxError: invalid syntax

**Comment by hanshuting** [comment]
upgrading to python 3.6 solved this problem for me

**Comment by jonasrauber** [comment]
Yep, Foolbox 3 requires Python 3.6
